### ISSUE TITLE
Invisible terrain on the map around spawn points

### ISSUE THREAD

**Issue by trundler-dev** [apetavern/sbox-terryform#58] opened 2021-11-28 00:11 UTC
![20211127201100_1](https://user-images.githubusercontent.com/57276947/143724091-bbc66fe3-1adb-4058-bd55-8c96e6edf98d.jpg)

**Comment by trundler-dev** [comment] 2021-11-28 00:12
Likely some kind of collision box for the worms/players

**Comment by Matt9440** [comment] 2021-11-28 02:10
If a worm has fallen through the floor, it's the worms bounding box. I've moved the spawn points up a bit on the projectile branch and haven't seen this since. Are you able to confirm?

**Comment by trundler-dev** [comment] 2021-11-28 03:50
Yep, I think this is fixed in your branch. Closing this.

**Comment by trundler-dev** [comment] 2021-11-28 17:30
Re-opening.

**Comment by Matt9440** [comment] 2021-12-01 07:51
I think I have this fixed on my branch. I believe it's caused by the Pawn.Players respawn method calling base - it creates a hull for the player which we don't actually need, fixed by not calling base.Respawn().

Will leave the issue open until we can confirm it's fixed.

**Comment by Matt9440** [comment] 2021-12-01 14:58
Haven't ran into this since.

**Closed by Matt9440** 2021-12-01 14:58 UTC
Labels: bug
